spring:
  datasource:
    hikari:
      max-lifetime: 600
#      connection-timeout: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    include:
      - jwt
      - aws
      - mybatis
    active: live   # local, alpha, live


# 허용하는 이미지 확장자
allow-image-format: "jpg,JPG,jpeg,JPEG,png,PNG,heic,HEIC"
