cloud:
  aws:
    credentials:
      accessKey: ENC(CMrNZQIf17VL36IdfWoSygPl/NMwyu1cnRxfyd6jcQU=)
      secretKey: ENC(cYzjMTXTP3sNvG2/BpjAgx+5BO4o/1unTQvhjtezAtXS2r/OcR1TjGhs4ZgvKZvXkNbTx3ndVdQ=)
    s3:
      bucket: sullog-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false