spring:
  config:
    import: "classpath:oauth-local.yml"
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: ENC(I82xieWlXOgnSdf9pob+XXhfPrqYKxsDRghOFNyRNSwogRP2Hw2gXb6AqHNQJR2VAfrSYLrpg9htdh+KUs68REgBNoCt87erFIC1/o8eLISxSs4fdsftalnOhjZ+WJQuz5oBo4IY8X9oWIxHPla8A3+o8WQ/l4wxUo8SQAqPACkbG31ETSs+864CCrd8GY1AWc3Bd3kX0YDIgMaoGf4d1hnSB8q062SEgt2Gvqj9l0GOFB+0lc14rCQEVJOeN80u/HzRqxnmzPo=)
    username: ENC(+s3VvY4FZ+n6yPic4s+FNtXAz9paqMRg)
    password: ENC(YcswAmAmRikB4To119ar4z9/h/PZwDvZ)
    hikari: # Connection Pool 설정 (Hikari CP가 해당 역할 수행)
      #        maximum-pool-size: 10
      #        connection-timeout: 5000
      #        connection-init-sql: SELECT 1
      #        validation-timeout: 2000
      #        minimum-idle: 10
      #        idle-timeout: 600000
      #        max-lifetime: 1800000
      max-lifetime: 6000 # Possibly consider using a shorter maxLifetime value.(10000 => 6000)

logging:
  level:
    jdbc:
      sqlonly: info
      sqltiming: info
      resultsettable: off
      audit: off
      resultset: off
      connection: off
  config: classpath:log4j2-local.yml

# CORS 이슈 대응
client-domains: "http://localhost:3000"

