spring:
  datasource:
    hikari:
      max-lifetime: 600
#      connection-timeout: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    include:
      - jwt
      - aws
      - mybatis
    active: alpha   # local, alpha, live
server:
  port: 8081

